name: Sync Shared Files
on:
  push:
    branches: [ main ]

jobs:
  test-release-script:
    name: Test Release Script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SOT Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements-dev.txt

      - name: Run tests
        run: pytest tests/

  sync-files:
    name: Sync to Destination Repos
    needs: test-release-script # Run only if tests pass
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [
            "UTEC-GmbH/QGIS-Plugin_Layer_Tools",
            "UTEC-GmbH/QGIS-Plugin_FW_Massenermittlung",
            "UTEC-GmbH/QGIS-Plugin_DHN",
          ]

    steps:
      - name: Checkout SOT Repo (shared files)
        uses: actions/checkout@v4

      - name: Checkout Destination Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
          token: ${{ secrets.SYNC_TOKEN }}
          path: dest_repo
          persist-credentials: true

      - name: Sync and Merge to Destinations
        run: |
          # 1. Setup Git identity
          git config --global user.name "SOT-Bot"
          git config --global user.email "actions@github.com"

          # 2. Sync everything from SOT root to dest_repo root
          rsync -av --exclude='.git' --exclude='.github' --exclude='dest_repo' --exclude='tests' ./ dest_repo/

          # 3. Commit and Push
          cd dest_repo
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes detected for ${{ matrix.repo }}"
          else
            git commit -m "SOT-Bot: updated from shared_files repo"
            git push origin main
          fi
